Works contents
cammelworks/CammelPages pull request #7
Opened 2020-10-02 15:14 UTC by Yamakatsu63

- ヘッダーのページ内リンクを押したときのアニメーションを追加
- aboutの文を変更
- worksにAR-Beats!とByeByeVirusを追加
- worksに詳細パネルを追加
- membersとworksの画像の下に名前を表示
- 詳細パネルが表示されるときのアニメーションを作成

2020-10-02 15:55 UTC, kugimasa requested changes
@Yamakatsu63 
レビューしました!
実装ありがとう！
動作は問題ないと思います。
何点か文章のtypoと提案をあげました。
修正をお願いします

2020-10-02 15:55 UTC, kugimasa commented on docs/src/works.js
> +プログラミンで使うキーは、”＃”だったり”;”だったり普通のタイピングソフトでは習えない…
typo
プログラミン => プログラミング

提案
タイピングソフト => タイピングゲーム

2020-10-02 15:55 UTC, kugimasa commented on docs/src/works.js
> +一人ではダイエットが続かない…3日坊主のあなたへ
「三日坊主」に統一した方がいいと思います

2020-10-02 15:55 UTC, kugimasa commented on docs/src/works.js
> +みんなとたくさんウイルスを消しましょう！
提案
「みんなとたくさんウイルスを消そう！」がいいかも

2020-10-03 06:43 UTC, Yamakatsu63 commented on docs/src/works.js
> +プログラミンで使うキーは、”＃”だったり”;”だったり普通のタイピングソフトでは習えない…
修正しました

2020-10-03 06:43 UTC, Yamakatsu63 commented on docs/src/works.js
> +一人ではダイエットが続かない…3日坊主のあなたへ
3日坊主を三日坊主に修正しました。

2020-10-03 06:43 UTC, Yamakatsu63 commented on docs/src/works.js
> +みんなとたくさんウイルスを消しましょう！
語尾を修正しました

2020-10-03 08:34 UTC, kugimasa approved these changes

2020-10-03 08:35 UTC, kugimasa commented
@Yamakatsu63 修正確認しました！
PR Approved🎉

2020-10-03 08:36 UTC, merged